
#manual trigger
trigger:
  branches:
    exclude:
      - '*'

variables:
  - template: variables.sb.yml


pool:
  name: Build

parameters:
  - name: ENVIROMENT_NAME
    type: string
    default: 'dv'

  - name: DATABRICKS_HOST
    type: string
    default: 'https://<yourdatabricksinstanceid>.azuredatabricks.net'

  - name: DATABRICKS_CLUSTER_CONFIG_FILE
    type: string
    default: 'environments/dv/databricks-sqlwarehouse/sql-warehouse.json'

  - name: AZURE_SUBSCRIPTION
    type: string
    default: 'sc-todo-sb-svcpri-dev'

#deploy databricks compute cluster

stages:
  - stage: DeployDatabricksCompute
    displayName: 'Deploy Databricks Compute'
    jobs:
    - job: DeployDatabricksCompute
      displayName: 'Deploy Databricks Compute'
      steps:
      - task: AzureCLI@2
        inputs:
          connectedServiceNameARM: ${{ parameters.AZURE_SUBSCRIPTION }}
          scriptType: 'ps'
          scriptLocation: 'scriptPath'
          scriptPath: '$(System.DefaultWorkingDirectory)/pipelines/scripts/databricks/databricks_sql_warehouse.ps1'
          arguments: -DatabricksHost ${{ parameters.DATABRICKS_HOST }} -ClusterConfigPath ${{ parameters.DATABRICKS_CLUSTER_CONFIG_FILE }} 

