variables:
#------------------------------------------------------------------
# Infra Pipeline Configuration
#------------------------------------------------------------------

#Agent Pool Name  
  - name: agentPool
    value: BuildWSL
  
#Azure Service Connection Name
  - name: azureServiceConnection
    #value: sc-unitycatalog-pr-svcpri-adm
    value: sc-todo-sb-svcpri-dev


#infrastructure configuration
  - name: resourceGroup
    value: rg-todo-sb-svcpri-dev
  - name: resourceType
    value: todo
  - name: environmentName
    value: dev
  - name: dryRun
    value: false