# **************************************************************************
#  Notes... deploy resources accodrding to the following sequence
# **************************************************************************
# =-> Deploy Log Analytics Workspace
# =-> Deploy Nat Gateway
# =-> Deploy Virtual Network
# =-> Deploy Data Storage Account
# =-> Deploy Meta Storage Account
# =-> Deploy Key Vault
# =-> Deploy Event Hub Namepsace
# =-> Deploy Data Factory
# =-> Deploy Databricks Workspace - Seperarate Workflow
# =-> Deploy DataBricks Access Connector - Seperarate Workflow
# ---------------------------------------------------------------------------

# name: CI Pipeline

# Define the events that trigger the workflow
# on:
#   # Set your workflow to run on push events to the develop and all feature branches
#   push:
#     branches:
#       - develop
#       - feature/*
#   # Set your workflow to run on pull request events that target the main branch
#   pull_request:
#     branches: 
#       - main


name: PS_DW_CI_AZ_INFRASTRUCTURE_DV

on:
  workflow_dispatch: 

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - uses: azure/login@v2
      with:
        creds: ${{ secrets.PS_DW_DV_AZ_CONN }}

    - name: Deploy BICEP Log Analytics Workspace
      uses: azure/cli@v2
      with:
        azcliversion: 2.63.0
        inlineScript: |   
          az account show --output table
          az deployment group create \
            --resource-group ps-dw-dv-rg \
            --template-file ../variables.dv.${{ parameters.templatefile}}  \
            --parameters "./lakehouse/environments/dv/_parameters.dv.json" \
            --parameters "./lakehouse/environments/dv/_parameters.log_analytics_workspace.json" \
            --name ps-dw-dv-log \
            --mode Incremental

    # - name: Deploy BICEP Nat Gateway
    #   uses: azure/cli@v2
    #   with:
    #     azcliversion: 2.63.0
    #     inlineScript: |
    #       az account show --output table
    #       az deployment group create \
    #         --resource-group ps-dw-dv-rg \
    #         --template-file "./lakehouse/common-config/nat_gateway.bicep" \
    #         --parameters "./lakehouse/environments/dv/_parameters.dv.json" \
    #         --parameters "./lakehouse/environments/dv/_parameters.nat_gateway.json" \
    #         --name ps-dw-dv-nat \
    #         --mode Incremental

    # - name: Deploy Virtual Network
    #   uses: azure/cli@v2
    #   with:
    #     azcliversion: 2.63.0
    #     inlineScript: |
    #       az account show --output table
    #       az deployment group create \
    #         --resource-group ps-dw-dv-rg \
    #         --template-file "./lakehouse/common-config/virtual_network.bicep" \
    #         --parameters "./lakehouse/environments/dv/_parameters.dv.json" \
    #         --parameters "./lakehouse/environments/dv/_parameters.virtual_network.json" \
    #         --name ps-dw-dv-vnet \
    #         --mode Incremental

    # - name: Deploy Data Storage Account
    #   uses: azure/cli@v2
    #   with:
    #     azcliversion: 2.63.0
    #     inlineScript: |
    #       az account show --output table
    #       az deployment group create \
    #         --resource-group ps-dw-dv-rg \
    #         --template-file "./lakehouse/common-config/storage_account_data.bicep" \
    #         --parameters "./lakehouse/environments/dv/_parameters.dv.json" \
    #         --parameters "./lakehouse/environments/dv/_parameters.storage_account_data.json" \
    #         --name psdwdvstordata \
    #         --mode Incremental

    # - name: Deploy Meta Storage Account
    #   uses: azure/cli@v2
    #   with:
    #     azcliversion: 2.63.0
    #     inlineScript: |
    #       az account show --output table
    #       az deployment group create \
    #         --resource-group ps-dw-dv-rg \
    #         --template-file "./lakehouse/common-config/storage_account_metastore.bicep" \
    #         --parameters "./lakehouse/environments/dv/_parameters.dv.json" \
    #         --parameters "./lakehouse/environments/dv/_parameters.storage_account_metastore.json" \
    #         --name psdwdvstormeta \
    #         --mode Incremental

    # - name: Deploy Key Vault
    #   uses: azure/cli@v2
    #   with:
    #     azcliversion: 2.63.0
    #     inlineScript: |
    #       az account show --output table
    #       az deployment group create \
    #         --resource-group ps-dw-dv-rg \
    #         --template-file "./lakehouse/common-config/key_vault.bicep" \
    #         --parameters "./lakehouse/environments/dv/_parameters.dv.json" \
    #         --parameters "./lakehouse/environments/dv/_parameters.key_vault.json" \
    #         --name ps-dw-dv-kv \
    #         --mode Incremental

# **********************************************************************************************************
#  Note...Seperate yml (ps-dw-dbx-wrkspace-cli-infra.)  to deploy databrcicks workspaces/ access connectors
# **********************************************************************************************************
    # - name: Deploy Databricks Workspace
    #   uses: azure/cli@v2
    #   with:
    #     azcliversion: 2.63.0
    #     inlineScript: |
    #       az account show --output table
    #       az deployment group create \
    #         --resource-group ps-dw-dv-rg \
    #         --template-file "./lakehouse/common-config/databricks_workspace.bicep" \
    #         --parameters "./lakehouse/environments/dv/_parameters.dv.json" \
    #         --parameters "./lakehouse/environments/dv/_parameters.databricks_workspace.json" \
    #         --name pps-dw-dv-dbx \
    #         --mode Incremental

    # - name: DataBricks Access Connector
    #   uses: azure/cli@v2
    #   with:
    #     azcliversion: 2.63.0
    #     inlineScript: |
    #       az account show --output table
    #       az deployment group create \
    #         --resource-group ps-dw-dv-rg \
    #         --template-file "./lakehouse/common-config/databricks_access_connector.bicep" \
    #         --parameters "./lakehouse/environments/dv/_parameters.dv.json" \
    #         --parameters "./lakehouse/environments/dv/_parameters.databricks_access_connector.json" \
    #         --name ps-dw-dv-conn-dbx \
    #         --mode Incremental
