on:
  push:
    branches: main

jobs:

  deploy:
    runs-on: ubuntu-latest
    name: Deploy Job
    env:
      template: ../Variables.${{ github.event.inputs.environmentName }}.yml
    steps:
    - name: checkout sourcecode
      uses: actions/checkout@v2
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run Azure CLI script
      run: |
        # Function to add parameters if file exists and is not empty
        add_params_if_exists() {
          if [ -s "$1" ]; then
            echo "--parameters $1"
          fi
        }

        # Construct the command dynamically
        cmd="az deployment group"
        if [[ "$DRYRUN" == "true" || "$DRYRUN" == "True" || "$DRYRUN" == true ]]; then
          echo -e "${GREEN}******Dry run enabled******${NC}"
          cmd+=" what-if"
        else
          echo -e "${GREEN}******Dry run disabled******${NC}"
          cmd+=" create"
        fi

        # Print the command
        echo "Executing command:"
        echo "$cmd"

        cmd+=" --resource-group ${{ github.event.inputs.resourceGroup }} --template-file common-config/${{ github.event.inputs.resourceType }}.bicep"
        cmd+=" $(add_params_if_exists "environments/${{ github.event.inputs.environmentName }}/_parameters.${{ github.event.inputs.environmentName }}.json")"
        cmd+=" $(add_params_if_exists "environments/${{ github.event.inputs.environmentName }}/_parameters.${{ github.event.inputs.resourceType }}.json")"
        
        # Print the command
        echo "Executing command:"
        echo "$cmd"
        DRYRUN: ${{ github.event.inputs.dryRun }}