# **************************************************************************
#  Notes... deploy resources accodrding to the following sequence
# **************************************************************************
# =-> Deploy Log Analytics Workspace
# =-> Deploy Nat Gateway
# =-> Deploy Virtual Network
# =-> Deploy Data Storage Account
# =-> Deploy Meta Storage Account
# =-> Deploy Key Vault
# =-> Deploy Event Hub Namepsace
# =-> Deploy Data Factory
# =-> Deploy Databricks Workspace
# =-> Deploy DataBricks Access Connector
# ---------------------------------------------------------------------------

name: CI Pipeline

# Define the events that trigger the workflow
# on:
#   push:
#     branches:
#       - main
#       - tested
#   pull_request:
#     branches:
#       - main
on:
  workflow_dispatch:

jobs:
  deploy-bicep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Azure Login action
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Deploy BICEP Log Analytics Workspace
        uses: azure/arm-deploy@v1
        with:
            subscriptionId: ${{ secrets.sAZURE_SUBSCRIPTION_ID }} #Subscription ID
            resourceGroupName: 'ps-dw-sb-rg'
            template: './modules/log_analytics_solution/main.bicep' # Path to your Bicep template
            parameters: './environments/sb/_parameters.log_analytics_workspace.json' # Path to your Bicep paramenter file
            deploymentName: 'bicep-deployment' #Name of the deployment
      
      #verify deployment
      - name: Verify Deployment
        run: |
          az deployment group show --name bicep-deployment --resource-group ps-dw-dv-rg --query properties.outputs --output table
