# **************************************************************************
#  Notes... deploy resources accodrding to the following sequence
# **************************************************************************
# =-> Deploy Log Analytics Workspace
# =-> Deploy Nat Gateway
# =-> Deploy Virtual Network
# =-> Deploy Data Storage Account
# =-> Deploy Meta Storage Account
# =-> Deploy Key Vault
# =-> Deploy Event Hub Namepsace
# =-> Deploy Data Factory
# =-> Deploy Databricks Workspace
# =-> Deploy DataBricks Access Connector
# ---------------------------------------------------------------------------

# name: CI Pipeline

# Define the events that trigger the workflow
# on:
#   # Set your workflow to run on push events to the develop and all feature branches
#   push:
#     branches:
#       - develop
#       - feature/*
#   # Set your workflow to run on pull request events that target the main branch
#   pull_request:
#     branches: 
#       - main


name: CI Pipeline

on:
  workflow_dispatch: 

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy BICEP Log Analytics Workspace
      uses: azure/cli@v2
      with:
        azcliversion: 2.63.0
        inlineScript: |   
            az account show --output table
            az deployment group create \
              --resource-group ps-dw-dv-rg \
              --template-file "./common-config/log_analytics_workspace.bicep" \
              --parameters "./environments/dv/_parameters.dv.json" \
              --parameters "./environments/dv/_parameters.log_analytics_workspace.json" \
              --name ps-dw-dv-log \
              --mode Incremental
  
    - name: Deploy BICEP Nat Gateway
      uses: azure/cli@v2
      with:
        azcliversion: 2.63.0
        inlineScript: |
            az account show --output table
            az deployment group create \
              --resource-group ps-dw-dv-rg \
              --template-file "./common-config/nat_gateway.bicep" \
              --parameters "./environments/dv/_parameters.dv.json" \
              --parameters "./environments/dv/_parameters.nat_gateway.json" \
              --name ps-dw-dv-nat \
              --mode Incremental
  
    - name: Deploy Virtual Network
      uses: azure/cli@v2
      with:
        azcliversion: 2.63.0
        inlineScript: |
            az account show --output table
            az deployment group create \
              --resource-group ps-dw-dv-rg \
              --template-file "./common-config/virtual_network.bicep" \
              --parameters "./environments/dv/_parameters.dv.json" \
              --parameters "./environments/dv/_parameters.virtual_network.json" \
              --name ps-dw-dv-vnet \
              --mode Incremental
    
    - name: Deploy Data Storage Account
      uses: azure/cli@v2
      with:
        azcliversion: 2.63.0
        inlineScript: |
            az account show --output table
            az deployment group create \
              --resource-group ps-dw-dv-rg \
              --template-file "./common-config/storage_account_data.bicep" \
              --parameters "./environments/dv/_parameters.dv.json" \
              --parameters "./environments/dv/_parameters.storage_account_data.json" \
              --name psdwdvstordata \
              --mode Incremental
    
    - name: Deploy Meta Storage Account
      uses: azure/cli@v2
      with:
        azcliversion: 2.63.0
        inlineScript: |
            az account show --output table
            az deployment group create \
              --resource-group ps-dw-dv-rg \
              --template-file "./common-config/storage_account_metastore.bicep" \
              --parameters "./environments/dv/_parameters.dv.json" \
              --parameters "./environments/dv/_parameters.storage_account_metastore.json" \
              --name psdwdvstormeta \
              --mode Incremental
    
    - name: Deploy Key Vault
      uses: azure/cli@v2
      with:
        azcliversion: 2.63.0
        inlineScript: |
            az account show --output table
            az deployment group create \
              --resource-group ps-dw-dv-rg \
              --template-file "./common-config/key_vault.bicep" \
              --parameters "./environments/dv/_parameters.dv.json" \
              --parameters "./environments/dv/_parameters.key_vault.json" \
              --name ps-dw-dv-kv \
              --mode Incremental
        
    - name: Deploy Databricks Workspace
      uses: azure/cli@v2
      with:
        azcliversion: 2.63.0
        inlineScript: |
            az account show --output table
            az deployment group create \
              --resource-group ps-dw-dv-rg \
              --template-file "./common-config/databricks_workspace.bicep" \
              --parameters "./environments/dv/_parameters.dv.json" \
              --parameters "./environments/dv/_parameters.databricks_workspace.json" \
              --name pps-dw-dv-dbx \
              --mode Incremental
        
    - name: DataBricks Access Connector
      uses: azure/cli@v2
      with:
        azcliversion: 2.63.0
        inlineScript: |
            az account show --output table
            az deployment group create \
              --resource-group ps-dw-dv-rg \
              --template-file "./common-config/databricks_access_connector.bicep" \
              --parameters "./environments/dv/_parameters.dv.json" \
              --parameters "./environments/dv/_parameters.databricks_access_connector.json" \
              --name ps-dw-dv-conn-dbx \
              --mode Incremental
            