# **************************************************************************
#  Notes... deploy resources accodrding to the following sequence
# **************************************************************************
# =-> Deploy Log Analytics Workspace
# =-> Deploy Nat Gateway
# =-> Deploy Virtual Network
# =-> Deploy Data Storage Account
# =-> Deploy Meta Storage Account
# =-> Deploy Key Vault
# =-> Deploy Event Hub Namepsace
# =-> Deploy Data Factory
# =-> Deploy Databricks Workspace
# =-> Deploy DataBricks Access Connector
# ---------------------------------------------------------------------------

name: CI Pipeline

# Define the events that trigger the workflow
# on:
#   push:
#     branches:
#       - main
#       - tested
#   pull_request:
#     branches:
#       - main
on:
  workflow_dispatch:

jobs:
  deploy-bicep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure Login action
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Azure PowerShell action
        uses: azure/powershell@v2
        with:
          azPSVersion: latest
          inlineScript: |

            $env = "sb"
            $rg = "ps-dw-sb-rg"
            $sb = ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            az account set --subscription $sb
            az account show --output table

            az deployment group create `
                --resource-group $rg `
                --template-file "./common-config/log_analytics_workspace.bicep" `
                --parameters "./environments/${env}/_parameters.${env}.json" `
                --parameters "./environments/${env}/_parameters.log_analytics_workspace.json" `
                --name "Deploy BICEP Log Analytics Workspace" `
                --mode Incremental `
